spring:
  application:
    name: see-system
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://60.205.112.175:13306/soeasyeasy?useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=Asia/Shanghai&allowPublicKeyRetrieval=true&useInformationSchema=true&nullNamePatternMatchesAll=true
    username: root
    password: 1hblsqt@mysql
  elasticsearch:
    uris: http://127.0.0.1:9200
    socket-timeout: 10s
logging:
  level:
    com:
      soeasyeasy: debug
server:
  port: 8081
  servlet:
    context-path: /system
---
#spring:
#  cloud:
#    nacos:
#      discovery:
#        server-addr: 127.0.0.1:8848 # Nacos æœåŠ¡å™¨åœ°å€
#        namespace: public # æˆ–ä½ æŒ‡å®šçš„å‘½åç©ºé—´
#        # å¦‚æœ Nacos å¯ç”¨äº†è®¤è¯
#        username: nacos   # ğŸ”‘ è¿™é‡Œè¦å†™æ­£ç¡®è´¦å·
#        password: 1hblsqt@nacos   # ğŸ”‘ è¿™é‡Œè¦å†™æ­£ç¡®å¯†ç 
#        group: business
#      config:
#        server-addr: 127.0.0.1:8848
#        namespace: 450533bf-73ac-4bee-a9f3-94ce306b9339
#        group: TENANT-META # æ–¹å¼1: åœ¨ bootstrap.yml ä¸­æŒ‡å®š group
#        file-extension: yaml
#        username: nacos   # ğŸ”‘ è¿™é‡Œè¦å†™æ­£ç¡®è´¦å·
#        password: 1hblsqt@nacos   # ğŸ”‘ è¿™é‡Œè¦å†™æ­£ç¡®å¯†ç 
#        # æ–¹å¼2: é€šè¿‡ shared-configs å¼•å…¥ç‰¹å®šé…ç½®
#        shared-configs:
#          - data-id: tenants.yaml
#            group: TENANT-META # æŒ‡å®šç§Ÿæˆ·é…ç½®æ‰€åœ¨çš„ç»„
#            refresh: true # å¼€å¯åŠ¨æ€åˆ·æ–°
#  # ğŸ‘‡ğŸ‘‡ğŸ‘‡ å…³é”®ï¼šæ˜¾å¼å¯¼å…¥ Nacos é…ç½® ğŸ‘‡ğŸ‘‡ğŸ‘‡
#  config:
#    import:
#      - nacos:tenants.yaml?group=TENANT-META&namespace=450533bf-73ac-4bee-a9f3-94ce306b9339&serverAddr=127.0.0.1:8848
